name: PhotonAPI
description: Unofficial dart api for use with Flutter apps.
author: Menno van Leeuwen <menno@vleeuwen.me>
homepage: https://github.com/vleeuwenmenno/photonapi

version: 1.0.0+1

dependencies:
  